using AssetTracker.Models;
using AssetTracker.Services;

public class SeedData
{
    public static void Initialize(AssetContext context, Dictionary<string, decimal> rates)
    {
        if (context.Assets.Any())
        {
            return; // Already seeded
        }

        else
        {
            // The sample data was generated by ChatGPT
            context.Assets.AddRange(
                AssetFactory.Create("Laptop", "Dell", "XPS 13", "Toronto", 1200m, DateTime.Parse("2023-05-01"), rates),
                AssetFactory.Create("Phone", "Apple", "iPhone 14", "Berlin", 999m, DateTime.Parse("2023-11-15"), rates),
                AssetFactory.Create("Laptop", "HP", "EliteBook 840", "Malmö", 1100m, DateTime.Parse("2021-07-01"), rates),
                AssetFactory.Create("Phone", "Samsung", "Galaxy S22", "Tokyo", 850m, DateTime.Parse("2022-09-01"), rates),
                AssetFactory.Create("Phone", "Google", "Pixel 7", "Malmö", 700m, DateTime.Parse("2023-02-28"), rates),
                AssetFactory.Create("Laptop", "MSI", "Prestige 14", "Boston", 1000m, DateTime.Parse("2022-06-10"), rates),
                AssetFactory.Create("Phone", "Sony", "Xperia 1 V", "Tokyo", 950m, DateTime.Parse("2022-12-15"), rates)
            );

            context.SaveChanges();
        }
    }
}

